---
- name: Install and manage Homebrew package on macOS
  hosts: localhost
  tasks:
    - name: Install a list of brew packages
      homebrew:
       name: "{{ item }}"
       state: present
      with_items:
       - git
       - wget
       - python
       - node


